USE WAREHOUSE ROHAN_BLAKE_KENNETH_WH;
USE DATABASE CS5542_LAB5_ROHAN_BLAKE_KENNETH;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

SELECT COUNT(*) AS raw_chunks FROM RAW.CHUNKS;
SELECT COUNT(*) AS app_chunks_v FROM APP.CHUNKS_V;

SELECT * FROM APP.CHUNKS_V LIMIT 5;