CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS APP;

CREATE OR REPLACE TABLE RAW.CHUNKS (
  EVIDENCE_ID STRING,
  DOC_ID STRING,
  SOURCE_FILE STRING,
  PAGE NUMBER,
  CHUNK_INDEX NUMBER,
  CHUNK_TEXT STRING
);