USE WAREHOUSE ROHAN_BLAKE_KENNETH_WH;
USE DATABASE CS5542_LAB5_ROHAN_BLAKE_KENNETH;

CREATE SCHEMA IF NOT EXISTS APP;

CREATE OR REPLACE VIEW APP.CHUNKS_V AS
SELECT
  EVIDENCE_ID,
  DOC_ID,
  SOURCE_FILE,
  PAGE,
  CHUNK_INDEX,
  CHUNK_TEXT
FROM RAW.CHUNKS;